# wenetaunthreader
# fuck spaces
# tabs for life

all:
	mkdir -p ../bins/jbin/
	$CC enjb.c -o ../bins/unthreader/bin/enjb
	$CC dajb.c -o ../bins/unthreader/bin/dajb
	$CC dajbar.c -o ../bins/unthreader/bin/dajbar
	$CC lifesupportd.c -o ../bins/unthreader/bin/lifesupportd
	$CC backbraced.c -o ../bins/unthreader/bin/backbraced

